spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/scarecrow?serverTimezone=GMT%2B8
    username: root
    password: a123456
    driver-class-name: com.mysql.cj.jdbc.Driver